__name__ = "lsabe-ma"
__version__ = "0.0.1"
__summary__ = "LSABE-MA algorithm"
__uri__ = "https://github.com/maxirmx/LSABE-MA"
__author__ = "Maxim Samsonov"
__email__ = "m.samsonov@computer.org"
__license__ = "MIT"