__name__ = "lsabe_ma_srv"
__version__ = "0.0.2"
__summary__ = "LSABE-MA Server"
__uri__ = "https://github.com/maxirmx/LSABE-MA"
__author__ = "Maxim Samsonov"
__email__ = "m.samsonov@computer.org"
__license__ = "MIT"