name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'  
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout LSABE_MA
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
        
    - name: Install
      run: sudo pip install .

    - name: Run
      run: python -m lsabe_ma
